# http://habrahabr.ru/post/155201/

SHELL=/bin/bash
CC=g++
CFLAGS=-std=c++11 -I../include

all:
	$(CC) $(CFLAGS) algorithms_1.cpp -o algorithms_1
	$(CC) $(CFLAGS) algorithms_2.cpp -o algorithms_2
	$(CC) $(CFLAGS) algorithms_3.cpp -o algorithms_3

clean:
	rm algorithms_1 algorithms_2 algorithms_3

