# http://habrahabr.ru/post/155201/

SHELL=/bin/bash
CC=g++
CFLAGS=-std=c++11 -I../include

all:
	$(CC) $(CFLAGS) containers_1.cpp -o containers_1
	$(CC) $(CFLAGS) containers_2.cpp -o containers_2
	$(CC) $(CFLAGS) containers_3.cpp -o containers_3

clean:
	rm containers_1 containers_2 containers_3

