#!/bin/bash

for file in *.cpp; do
  base=$(basename "$file")
  binary="${base%.*}"
  g++ -std=c++11 -I../include $file -o $binary
done

./class_0 #; read -p "Press any key to continue"
./class_1 #; read -p "Press any key to continue"
./class_2 #; read -p "Press any key to continue"
./class_3 #; read -p "Press any key to continue"
./class_4 #; read -p "Press any key to continue"
./class_5 #; read -p "Press any key to continue"
./class_5_1 ; read -p "Press any key to continue"
./class_5_2 #; read -p "Press any key to continue"
./class_5_3 #; read -p "Press any key to continue"
./class_5_4 #; read -p "Press any key to continue"
./class_5_5 #; read -p "Press any key to continue"
./class_5_6 ; read -p "Press any key to continue"
./class_5_7 ; read -p "Press any key to continue"
./class_5_7_1 ; read -p "Press any key to continue"
./class_5_8 ; read -p "Press any key to continue"
./class_5_8_1 #; read -p "Press any key to continue"

rm ./class_0
rm ./class_1
rm ./class_1_1
rm ./class_2
rm ./class_3
rm ./class_4
rm ./class_5
rm ./class_5_1
rm ./class_5_2
rm ./class_5_3
rm ./class_5_4
rm ./class_5_5
rm ./class_5_6
rm ./class_5_7
rm ./class_5_7_1
rm ./class_5_8
rm ./class_5_8_1

