#!/bin/bash

g++ -ggdb3 -O0 -I../.. ../memory_2.cpp -o memory_2_debug

# gdb memory_2_debug
# break main
# run
# next
# ...
# Введите первую строку: Hello
# next
# ...
# Введите вторую строку: Hello
# print first
# print second
# quit
# yes

