# http://habrahabr.ru/post/155201/

SHELL=/bin/bash
CC=g++
CFLAGS=-std=c++11 -I../../include

all:
	$(CC) $(CFLAGS) templates_5.cpp -o templates_5
	$(CC) $(CFLAGS) templates_6.cpp -o templates_6
	$(CC) $(CFLAGS) templates_7.cpp -o templates_7
	$(CC) $(CFLAGS) templates_8.cpp -o templates_8
	$(CC) $(CFLAGS) templates_9.cpp -o templates_9

clean:
	rm templates_5 templates_6 templates_7 templates_8 templates_9

