#!/bin/bash

for file in *.cpp; do
  base=$(basename "$file")
  binary="${base%.*}"
  g++ -std=c++11 -I../include $file -o $binary
done

./class_6 ; read -p "Press any key to continue"
./class_6_0 ; read -p "Press any key to continue"
./class_6_0_1 ; read -p "Press any key to continue"
./class_6_1 ; read -p "Press any key to continue"
./class_6_2 ; read -p "Press any key to continue"
./class_6_3 ; read -p "Press any key to continue"
./class_6_3_1 ; read -p "Press any key to continue"
./class_6_3_2 ; read -p "Press any key to continue"
./class_6_3_3 ; read -p "Press any key to continue"
./class_6_4 ; read -p "Press any key to continue"
./class_6_4_1 ; read -p "Press any key to continue"
./class_6_4_2 ; read -p "Press any key to continue"

rm ./class_6
rm ./class_6_0
rm ./class_6_0_1
rm ./class_6_1
rm ./class_6_2
rm ./class_6_3
rm ./class_6_3_1
rm ./class_6_3_2
rm ./class_6_3_3
rm ./class_6_4
rm ./class_6_4_1
rm ./class_6_4_2

