# http://habrahabr.ru/post/155201/

SHELL=/bin/bash
CC=g++
CFLAGS=-std=c++11 -I../include

all:
	$(CC) $(CFLAGS) templates_1.cpp -o templates_1
	$(CC) $(CFLAGS) templates_2.cpp -o templates_2
	$(CC) $(CFLAGS) templates_3.cpp -o templates_3

clean:
	rm templates_1 templates_2 templates_3

