# http://habrahabr.ru/post/155201/

SHELL=/bin/bash
CC=g++
CFLAGS=-std=c++11 -I../include

all:
	$(CC) $(CFLAGS) hashing_1.cpp -o hashing_1
	$(CC) $(CFLAGS) hashing_2.cpp -o hashing_2
	$(CC) $(CFLAGS) hashing_3.cpp -o hashing_3

clean:
	rm hashing_1 hashing_2 hashing_3

